from __future__ import annotations

import os
from functools import cached_property
from typing import Any

import mlflow
import mlflow.sklearn
import pandas as pd
from mlflow.tracking import MlflowClient

from features.ai4i import build_ai4i_features
from training.constants import CHAMPION_ALIAS, FEATURE_COLUMNS, MODEL_NAME, RISK_THRESHOLDS


def _tracking_uri() -> str:
    return os.getenv("MLFLOW_TRACKING_URI", "http://localhost:5000")


def _risk_class(probability: float) -> str:
    if probability >= RISK_THRESHOLDS["high"]:
        return "high"
    if probability >= RISK_THRESHOLDS["medium"]:
        return "medium"
    return "low"


class ModelServingService:
    """Loads approved predictive-maintenance models and serves predictions."""

    @cached_property
    def model(self) -> Any:
        mlflow.set_tracking_uri(_tracking_uri())
        return mlflow.sklearn.load_model(f"models:/{MODEL_NAME}@{CHAMPION_ALIAS}")

    @cached_property
    def model_version(self) -> str | None:
        try:
            mlflow.set_tracking_uri(_tracking_uri())
            version = MlflowClient().get_model_version_by_alias(MODEL_NAME, CHAMPION_ALIAS)
            return str(version.version)
        except Exception:
            return None

    def predict_failure(
        self,
        observation: dict[str, object],
        request_id: str | None = None,
    ) -> dict[str, object]:
        try:
            frame = pd.DataFrame(
                [
                    {
                        "udi": 0,
                        "product_id": "online-request",
                        "product_type": str(observation["product_type"]).upper(),
                        "air_temperature_k": float(observation["air_temperature_k"]),
                        "process_temperature_k": float(observation["process_temperature_k"]),
                        "rotational_speed_rpm": float(observation["rotational_speed_rpm"]),
                        "torque_nm": float(observation["torque_nm"]),
                        "tool_wear_min": float(observation["tool_wear_min"]),
                    }
                ]
            )
            features = build_ai4i_features(frame)
            features = features.rename(
                columns={
                    "type_H": "type_h",
                    "type_L": "type_l",
                    "type_M": "type_m",
                }
            )
            x = features[FEATURE_COLUMNS]
            probability = float(self.model.predict_proba(x)[0, 1])
            return {
                "status": "ok",
                "failure_probability": probability,
                "risk_class": _risk_class(probability),
                "model_version": self.model_version,
                "message": "Prediction generated by the registered MLflow champion model.",
                "metadata": {
                    "request_id": request_id,
                    "model_name": MODEL_NAME,
                    "model_alias": CHAMPION_ALIAS,
                    "feature_columns": FEATURE_COLUMNS,
                },
            }
        except Exception as exc:
            return {
                "status": "not_ready",
                "failure_probability": None,
                "risk_class": None,
                "model_version": None,
                "message": (
                    "Model serving is not ready yet. Run ingestion and training, then make sure "
                    "MLflow has a registered champion model."
                ),
                "metadata": {
                    "request_id": request_id,
                    "received_observation": observation,
                    "target": "Machine failure",
                    "error": str(exc),
                },
            }


_service = ModelServingService()


def get_model_serving_service() -> ModelServingService:
    return _service
