from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from monitoring.drift import latest_drift_report
from platform_api.config import Settings, get_settings

router = APIRouter()


class MonitoringStatusResponse(BaseModel):
    status: str
    metrics: list[str]
    message: str
    latest_report: str | None = None
    drift: dict[str, object] = Field(default_factory=dict)


@router.get(
    "/status",
    response_model=MonitoringStatusResponse,
    summary="Get monitoring integration status",
    description=(
        "Returns expected operational metrics and the latest PSI drift report generated by "
        "the Prefect monitoring flow."
    ),
)
def monitoring_status(settings: Settings = Depends(get_settings)) -> MonitoringStatusResponse:
    report = latest_drift_report(settings.drift_report_dir)
    if report:
        summary = report.get("summary", {})
        return MonitoringStatusResponse(
            status=str(report.get("status", "unknown")),
            metrics=[
                "prediction_requests_total",
                "prediction_latency_seconds",
                "prediction_risk_class_total",
                "chat_requests_total",
                "agent_tool_calls_total",
                "rag_search_requests_total",
                "rag_search_latency_seconds",
                "max_feature_psi",
                "drifted_feature_count",
            ],
            message="Latest PSI drift report loaded successfully.",
            latest_report=report.get("json_report_path")
            if isinstance(report.get("json_report_path"), str)
            else None,
            drift={
                "generated_at": report.get("generated_at"),
                "max_feature_psi": summary.get("max_feature_psi")
                if isinstance(summary, dict)
                else None,
                "drifted_features": summary.get("drifted_features")
                if isinstance(summary, dict)
                else [],
                "warning_features": summary.get("warning_features")
                if isinstance(summary, dict)
                else [],
            },
        )

    return MonitoringStatusResponse(
        status="not_configured",
        metrics=[
            "prediction_requests_total",
            "prediction_latency_seconds",
            "prediction_risk_class_total",
            "chat_requests_total",
            "agent_tool_calls_total",
            "rag_search_requests_total",
            "rag_search_latency_seconds",
            "feature_psi",
        ],
        message=(
            "Prometheus metrics are exposed at /metrics. Run the detect-ai4i-drift Prefect "
            "deployment to generate the first PSI drift report."
        ),
    )
